export const backgrounds = [
  'background-2.jpg',
  'background-3.jpg',
  'background-4.jpg',
  'background-6.jpg',
  'background-7.jpg',
  'background-8.jpg',
  'background-10.jpg',
  'background-11.jpg',
  'background-12.jpg',
  'background-13.jpg',
  'background-14.jpg',
  'background-15.jpg',
  'background-16.jpg',
  'background-17.jpg',
];
